spring:
  rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

account:
  exchange:
  name: account-exchange
  
  queue:
    name: account-queue
  routing: 
    name: account-routing-key